PeerOrgs:
  - Name: BANK01
    Domain: bank01.finance-trust.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 3
  - Name: REG01
    Domain: amf-regulateur.finance-trust.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
OrdererOrgs:
  - Name: Orderer
    Domain: finance-trust.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
