FROM golang:1.21-alpine AS builder
WORKDIR /chaincode
COPY . .
RUN go build -o chaincode ./cmd/rwa-token

FROM alpine:latest
WORKDIR /chaincode
COPY --from=builder /chaincode/chaincode .
EXPOSE 9999
CMD ["./chaincode"]
