# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: organizations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'organizations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13organizations.proto\x12\x11rwa.organizations\"0\n\x0fListOrgsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"G\n\x0bOrgResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06msp_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"@\n\x07OrgList\x12\x35\n\rorganizations\x18\x01 \x03(\x0b\x32\x1e.rwa.organizations.OrgResponse\"P\n\x10ListUsersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\"\x84\x02\n\x0bUserSummary\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t\x12\x12\n\ndepartment\x18\x06 \x01(\t\x12\x13\n\x0b\x65mployee_id\x18\x07 \x01(\t\x12\r\n\x05phone\x18\x08 \x01(\t\x12\x0e\n\x06msp_id\x18\t \x01(\t\x12\x13\n\x0bmfa_enabled\x18\n \x01(\x08\x12\x11\n\tis_active\x18\x0b \x01(\x08\x12\x0e\n\x06org_id\x18\x0c \x01(\t\x12\x10\n\x08org_name\x18\r \x01(\t\x12\x13\n\x0borg_country\x18\x0e \x01(\t\"9\n\x08UserList\x12-\n\x05users\x18\x01 \x03(\x0b\x32\x1e.rwa.organizations.UserSummary\"\"\n\x10PortfolioRequest\x12\x0e\n\x06org_id\x18\x01 \x01(\t\"\\\n\x11PortfolioResponse\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x1a\n\x12total_assets_value\x18\x02 \x01(\x01\x12\x1b\n\x13\x61\x63tive_assets_count\x18\x03 \x01(\x05\x32\x95\x02\n\x14OrganizationsService\x12S\n\x11ListOrganizations\x12\".rwa.organizations.ListOrgsRequest\x1a\x1a.rwa.organizations.OrgList\x12M\n\tListUsers\x12#.rwa.organizations.ListUsersRequest\x1a\x1b.rwa.organizations.UserList\x12Y\n\x0cGetPortfolio\x12#.rwa.organizations.PortfolioRequest\x1a$.rwa.organizations.PortfolioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'organizations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTORGSREQUEST']._serialized_start=42
  _globals['_LISTORGSREQUEST']._serialized_end=90
  _globals['_ORGRESPONSE']._serialized_start=92
  _globals['_ORGRESPONSE']._serialized_end=163
  _globals['_ORGLIST']._serialized_start=165
  _globals['_ORGLIST']._serialized_end=229
  _globals['_LISTUSERSREQUEST']._serialized_start=231
  _globals['_LISTUSERSREQUEST']._serialized_end=311
  _globals['_USERSUMMARY']._serialized_start=314
  _globals['_USERSUMMARY']._serialized_end=574
  _globals['_USERLIST']._serialized_start=576
  _globals['_USERLIST']._serialized_end=633
  _globals['_PORTFOLIOREQUEST']._serialized_start=635
  _globals['_PORTFOLIOREQUEST']._serialized_end=669
  _globals['_PORTFOLIORESPONSE']._serialized_start=671
  _globals['_PORTFOLIORESPONSE']._serialized_end=763
  _globals['_ORGANIZATIONSSERVICE']._serialized_start=766
  _globals['_ORGANIZATIONSSERVICE']._serialized_end=1043
# @@protoc_insertion_point(module_scope)
