# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from backend.grpc_generated import organizations_pb2 as organizations__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in organizations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrganizationsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListOrganizations = channel.unary_unary(
                '/rwa.organizations.OrganizationsService/ListOrganizations',
                request_serializer=organizations__pb2.ListOrgsRequest.SerializeToString,
                response_deserializer=organizations__pb2.OrgList.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/rwa.organizations.OrganizationsService/ListUsers',
                request_serializer=organizations__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=organizations__pb2.UserList.FromString,
                _registered_method=True)
        self.GetPortfolio = channel.unary_unary(
                '/rwa.organizations.OrganizationsService/GetPortfolio',
                request_serializer=organizations__pb2.PortfolioRequest.SerializeToString,
                response_deserializer=organizations__pb2.PortfolioResponse.FromString,
                _registered_method=True)


class OrganizationsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListOrganizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrganizationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=organizations__pb2.ListOrgsRequest.FromString,
                    response_serializer=organizations__pb2.OrgList.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=organizations__pb2.ListUsersRequest.FromString,
                    response_serializer=organizations__pb2.UserList.SerializeToString,
            ),
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=organizations__pb2.PortfolioRequest.FromString,
                    response_serializer=organizations__pb2.PortfolioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.organizations.OrganizationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.organizations.OrganizationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrganizationsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.organizations.OrganizationsService/ListOrganizations',
            organizations__pb2.ListOrgsRequest.SerializeToString,
            organizations__pb2.OrgList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.organizations.OrganizationsService/ListUsers',
            organizations__pb2.ListUsersRequest.SerializeToString,
            organizations__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.organizations.OrganizationsService/GetPortfolio',
            organizations__pb2.PortfolioRequest.SerializeToString,
            organizations__pb2.PortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
