# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from backend.grpc_generated import transactions_pb2 as transactions__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transactions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTransactions = channel.unary_unary(
                '/rwa.transactions.TransactionsService/ListTransactions',
                request_serializer=transactions__pb2.ListRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionList.FromString,
                _registered_method=True)
        self.GetTransactionStats = channel.unary_unary(
                '/rwa.transactions.TransactionsService/GetTransactionStats',
                request_serializer=transactions__pb2.StatsRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionStats.FromString,
                _registered_method=True)
        self.GetTransaction = channel.unary_unary(
                '/rwa.transactions.TransactionsService/GetTransaction',
                request_serializer=transactions__pb2.TxRefRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionResponse.FromString,
                _registered_method=True)


class TransactionsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTransactions,
                    request_deserializer=transactions__pb2.ListRequest.FromString,
                    response_serializer=transactions__pb2.TransactionList.SerializeToString,
            ),
            'GetTransactionStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionStats,
                    request_deserializer=transactions__pb2.StatsRequest.FromString,
                    response_serializer=transactions__pb2.TransactionStats.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=transactions__pb2.TxRefRequest.FromString,
                    response_serializer=transactions__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.transactions.TransactionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.transactions.TransactionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.transactions.TransactionsService/ListTransactions',
            transactions__pb2.ListRequest.SerializeToString,
            transactions__pb2.TransactionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.transactions.TransactionsService/GetTransactionStats',
            transactions__pb2.StatsRequest.SerializeToString,
            transactions__pb2.TransactionStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.transactions.TransactionsService/GetTransaction',
            transactions__pb2.TxRefRequest.SerializeToString,
            transactions__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
