# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zkp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zkp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tzkp.proto\x12\x07rwa.zkp\"=\n\x0fSetupKeyRequest\x12\x14\n\x0cpublic_key_x\x18\x01 \x01(\t\x12\x14\n\x0cpublic_key_y\x18\x02 \x01(\t\"}\n\x10SetupKeyResponse\x12\x15\n\rcredential_id\x18\x01 \x01(\t\x12\r\n\x05\x63laim\x18\x02 \x01(\t\x12\x12\n\nissuer_sig\x18\x03 \x01(\t\x12\x12\n\nexpires_at\x18\x04 \x01(\t\x12\x1b\n\x13sanctions_tree_root\x18\x05 \x01(\t\"\xd6\x01\n\x0cProofRequest\x12\x14\n\x0cpublic_key_x\x18\x01 \x01(\t\x12\x14\n\x0cpublic_key_y\x18\x02 \x01(\t\x12\x10\n\x08proof_rx\x18\x03 \x01(\t\x12\x10\n\x08proof_ry\x18\x04 \x01(\t\x12\x0f\n\x07proof_s\x18\x05 \x01(\t\x12\x0f\n\x07purpose\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x07 \x01(\t\x12\x11\n\tnullifier\x18\x08 \x01(\t\x12\x18\n\x10\x63redential_claim\x18\t \x01(\t\x12\x16\n\x0e\x63redential_sig\x18\n \x01(\t\"@\n\rProofResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07purpose\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"\xcf\x01\n\x11ZKPStatusResponse\x12\x15\n\rcredential_id\x18\x01 \x01(\t\x12\x16\n\x0ehas_credential\x18\x02 \x01(\x08\x12\x0e\n\x06\x61ge_ok\x18\x03 \x01(\x08\x12\x0e\n\x06kyc_ok\x18\x04 \x01(\x08\x12\x16\n\x0enot_sanctioned\x18\x05 \x01(\x08\x12\x11\n\tkyc_level\x18\x06 \x01(\x05\x12\x12\n\nexpires_at\x18\x07 \x01(\t\x12\x0f\n\x07revoked\x18\x08 \x01(\x08\x12\x1b\n\x13sanctions_tree_root\x18\t \x01(\t\"6\n\rRevokeRequest\x12\x15\n\rcredential_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"7\n\x0eRevokeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rcredential_id\x18\x02 \x01(\t2\x94\x02\n\nZKPService\x12?\n\x08SetupKey\x12\x18.rwa.zkp.SetupKeyRequest\x1a\x19.rwa.zkp.SetupKeyResponse\x12<\n\x0bVerifyProof\x12\x15.rwa.zkp.ProofRequest\x1a\x16.rwa.zkp.ProofResponse\x12\x42\n\x0cGetZKPStatus\x12\x16.rwa.zkp.StatusRequest\x1a\x1a.rwa.zkp.ZKPStatusResponse\x12\x43\n\x10RevokeCredential\x12\x16.rwa.zkp.RevokeRequest\x1a\x17.rwa.zkp.RevokeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETUPKEYREQUEST']._serialized_start=22
  _globals['_SETUPKEYREQUEST']._serialized_end=83
  _globals['_SETUPKEYRESPONSE']._serialized_start=85
  _globals['_SETUPKEYRESPONSE']._serialized_end=210
  _globals['_PROOFREQUEST']._serialized_start=213
  _globals['_PROOFREQUEST']._serialized_end=427
  _globals['_PROOFRESPONSE']._serialized_start=429
  _globals['_PROOFRESPONSE']._serialized_end=493
  _globals['_STATUSREQUEST']._serialized_start=495
  _globals['_STATUSREQUEST']._serialized_end=510
  _globals['_ZKPSTATUSRESPONSE']._serialized_start=513
  _globals['_ZKPSTATUSRESPONSE']._serialized_end=720
  _globals['_REVOKEREQUEST']._serialized_start=722
  _globals['_REVOKEREQUEST']._serialized_end=776
  _globals['_REVOKERESPONSE']._serialized_start=778
  _globals['_REVOKERESPONSE']._serialized_end=833
  _globals['_ZKPSERVICE']._serialized_start=836
  _globals['_ZKPSERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
