Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../crypto-config/ordererOrganizations/finance-trust.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &BANK01
    Name: BANK01MSP
    ID: BANK01MSP
    MSPDir: ../crypto-config/peerOrganizations/bank01.finance-trust.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BANK01MSP.admin', 'BANK01MSP.peer', 'BANK01MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BANK01MSP.admin', 'BANK01MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BANK01MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BANK01MSP.peer')"

  - &REG01
    Name: REG01MSP
    ID: REG01MSP
    MSPDir: ../crypto-config/peerOrganizations/reg01-regulateur.finance-trust.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('REG01MSP.admin', 'REG01MSP.peer', 'REG01MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('REG01MSP.admin', 'REG01MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('REG01MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('REG01MSP.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.finance-trust.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.finance-trust.com
        Port: 7050
        ClientTLSCert: ../crypto-config/ordererOrganizations/finance-trust.com/orderers/orderer.finance-trust.com/tls/server.crt
        ServerTLSCert: ../crypto-config/ordererOrganizations/finance-trust.com/orderers/orderer.finance-trust.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  RWAGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *BANK01
        - *REG01
