name: rwa-network
version: "1.0"
client:
  organization: BANK01
  connection:
    timeout:
      peer:
        endorser: "300"

organizations:
  BANK01:
    mspid: BANK01MSP
    peers:
      - peer0.bank01.finance-trust.com
    certificateAuthorities:
      - ca.bank01.finance-trust.com

  REG01:
    mspid: REG01MSP
    peers:
      - peer0.reg01-regulateur.finance-trust.com
    certificateAuthorities:
      - ca.reg01-regulateur.finance-trust.com

peers:
  peer0.bank01.finance-trust.com:
    url: grpcs://127.0.0.1:7051
    tlsCACerts:
      path: ./crypto-config/peerOrganizations/bank01.finance-trust.com/peers/peer0.bank01.finance-trust.com/tls/ca.crt
    grpcOptions:
      ssl-target-name-override: peer0.bank01.finance-trust.com
      hostnameOverride: peer0.bank01.finance-trust.com

  peer0.reg01-regulateur.finance-trust.com:
    url: grpcs://127.0.0.1:7091
    tlsCACerts:
      path: ./crypto-config/peerOrganizations/reg01-regulateur.finance-trust.com/peers/peer0.reg01-regulateur.finance-trust.com/tls/ca.crt
    grpcOptions:
      ssl-target-name-override: peer0.reg01-regulateur.finance-trust.com
      hostnameOverride: peer0.reg01-regulateur.finance-trust.com

certificateAuthorities:
  ca.bank01.finance-trust.com:
    url: https://127.0.0.1:7054
    caName: ca-bank01

  ca.reg01-regulateur.finance-trust.com:
    url: https://127.0.0.1:7154
    caName: ca-reg01

channels:
  rwa-channel:
    peers:
      peer0.bank01.finance-trust.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.reg01-regulateur.finance-trust.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
