#!/usr/bin/env bash
# Regenerate Python gRPC stubs from proto definitions.
# Run this after any change to a .proto file.
#
# Requirements:
#   pip install grpcio-tools

set -euo pipefail

PROTO_DIR="$(git rev-parse --show-toplevel)/proto"
OUT_DIR="$(git rev-parse --show-toplevel)/core/grpc_generated"

mkdir -p "$OUT_DIR"

python -m grpc_tools.protoc \
  --proto_path="$PROTO_DIR" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$PROTO_DIR"/*.proto

# Fix absolute imports generated by protoc → relative package imports.
# protoc emits `import assets_pb2 as assets__pb2` but our package is
# core.grpc_generated, so we need `from core.grpc_generated import …`
sed -i 's/^import \(.*_pb2\) as /from core.grpc_generated import \1 as /g' \
  "$OUT_DIR"/*_pb2_grpc.py

echo "Stubs generated in $OUT_DIR"
