# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from core.grpc_generated import assets_pb2 as assets__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in assets_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssetsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TokenizeAsset = channel.unary_unary(
                '/rwa.assets.AssetsService/TokenizeAsset',
                request_serializer=assets__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=assets__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.TransferAsset = channel.unary_unary(
                '/rwa.assets.AssetsService/TransferAsset',
                request_serializer=assets__pb2.TransferRequest.SerializeToString,
                response_deserializer=assets__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.FreezeAsset = channel.unary_unary(
                '/rwa.assets.AssetsService/FreezeAsset',
                request_serializer=assets__pb2.FreezeRequest.SerializeToString,
                response_deserializer=assets__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.UnfreezeAsset = channel.unary_unary(
                '/rwa.assets.AssetsService/UnfreezeAsset',
                request_serializer=assets__pb2.UnfreezeRequest.SerializeToString,
                response_deserializer=assets__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.GetAsset = channel.unary_unary(
                '/rwa.assets.AssetsService/GetAsset',
                request_serializer=assets__pb2.AssetIdRequest.SerializeToString,
                response_deserializer=assets__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.GetAssetHistory = channel.unary_unary(
                '/rwa.assets.AssetsService/GetAssetHistory',
                request_serializer=assets__pb2.AssetIdRequest.SerializeToString,
                response_deserializer=assets__pb2.ProvenanceResponse.FromString,
                _registered_method=True)
        self.SearchAssets = channel.unary_unary(
                '/rwa.assets.AssetsService/SearchAssets',
                request_serializer=assets__pb2.SearchRequest.SerializeToString,
                response_deserializer=assets__pb2.AssetList.FromString,
                _registered_method=True)
        self.ValuateAsset = channel.unary_unary(
                '/rwa.assets.AssetsService/ValuateAsset',
                request_serializer=assets__pb2.ValuateRequest.SerializeToString,
                response_deserializer=assets__pb2.ValuationResponse.FromString,
                _registered_method=True)
        self.ListAssetValuations = channel.unary_unary(
                '/rwa.assets.AssetsService/ListAssetValuations',
                request_serializer=assets__pb2.AssetIdRequest.SerializeToString,
                response_deserializer=assets__pb2.ValuationList.FromString,
                _registered_method=True)


class AssetsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def TokenizeAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreezeAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnfreezeAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValuateAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssetValuations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TokenizeAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenizeAsset,
                    request_deserializer=assets__pb2.TokenizeRequest.FromString,
                    response_serializer=assets__pb2.AssetResponse.SerializeToString,
            ),
            'TransferAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferAsset,
                    request_deserializer=assets__pb2.TransferRequest.FromString,
                    response_serializer=assets__pb2.AssetResponse.SerializeToString,
            ),
            'FreezeAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.FreezeAsset,
                    request_deserializer=assets__pb2.FreezeRequest.FromString,
                    response_serializer=assets__pb2.AssetResponse.SerializeToString,
            ),
            'UnfreezeAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.UnfreezeAsset,
                    request_deserializer=assets__pb2.UnfreezeRequest.FromString,
                    response_serializer=assets__pb2.AssetResponse.SerializeToString,
            ),
            'GetAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsset,
                    request_deserializer=assets__pb2.AssetIdRequest.FromString,
                    response_serializer=assets__pb2.AssetResponse.SerializeToString,
            ),
            'GetAssetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetHistory,
                    request_deserializer=assets__pb2.AssetIdRequest.FromString,
                    response_serializer=assets__pb2.ProvenanceResponse.SerializeToString,
            ),
            'SearchAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAssets,
                    request_deserializer=assets__pb2.SearchRequest.FromString,
                    response_serializer=assets__pb2.AssetList.SerializeToString,
            ),
            'ValuateAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.ValuateAsset,
                    request_deserializer=assets__pb2.ValuateRequest.FromString,
                    response_serializer=assets__pb2.ValuationResponse.SerializeToString,
            ),
            'ListAssetValuations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAssetValuations,
                    request_deserializer=assets__pb2.AssetIdRequest.FromString,
                    response_serializer=assets__pb2.ValuationList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.assets.AssetsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.assets.AssetsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TokenizeAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/TokenizeAsset',
            assets__pb2.TokenizeRequest.SerializeToString,
            assets__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/TransferAsset',
            assets__pb2.TransferRequest.SerializeToString,
            assets__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreezeAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/FreezeAsset',
            assets__pb2.FreezeRequest.SerializeToString,
            assets__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnfreezeAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/UnfreezeAsset',
            assets__pb2.UnfreezeRequest.SerializeToString,
            assets__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/GetAsset',
            assets__pb2.AssetIdRequest.SerializeToString,
            assets__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/GetAssetHistory',
            assets__pb2.AssetIdRequest.SerializeToString,
            assets__pb2.ProvenanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/SearchAssets',
            assets__pb2.SearchRequest.SerializeToString,
            assets__pb2.AssetList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValuateAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/ValuateAsset',
            assets__pb2.ValuateRequest.SerializeToString,
            assets__pb2.ValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAssetValuations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.assets.AssetsService/ListAssetValuations',
            assets__pb2.AssetIdRequest.SerializeToString,
            assets__pb2.ValuationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
