# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udit.proto\x12\trwa.audit\"1\n\x10\x41uditListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"\x8c\x01\n\rAuditLogEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x13\n\x0bstatus_code\x18\x05 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x06 \x01(\x05\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"9\n\x0c\x41uditLogList\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.rwa.audit.AuditLogEntry\"%\n\x11\x41ssetTrailRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\"W\n\x12\x41ssetTrailResponse\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x10\n\x08verified\x18\x02 \x01(\x08\x12\x1d\n\x15\x62lockchain_provenance\x18\x03 \x01(\t\"%\n\x11GenerateReportReq\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\"@\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\" \n\rTaskIdRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"W\n\x12TaskStatusResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x12\n\x10\x46raudScanRequest2\x84\x03\n\x0c\x41uditService\x12\x45\n\rListAuditLogs\x12\x1b.rwa.audit.AuditListRequest\x1a\x17.rwa.audit.AuditLogList\x12N\n\x0f\x46\x65tchAssetTrail\x12\x1c.rwa.audit.AssetTrailRequest\x1a\x1d.rwa.audit.AssetTrailResponse\x12G\n\x0eGenerateReport\x12\x1c.rwa.audit.GenerateReportReq\x1a\x17.rwa.audit.TaskResponse\x12J\n\x0fGetReportStatus\x12\x18.rwa.audit.TaskIdRequest\x1a\x1d.rwa.audit.TaskStatusResponse\x12H\n\x10TriggerFraudScan\x12\x1b.rwa.audit.FraudScanRequest\x1a\x17.rwa.audit.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDITLISTREQUEST']._serialized_start=26
  _globals['_AUDITLISTREQUEST']._serialized_end=75
  _globals['_AUDITLOGENTRY']._serialized_start=78
  _globals['_AUDITLOGENTRY']._serialized_end=218
  _globals['_AUDITLOGLIST']._serialized_start=220
  _globals['_AUDITLOGLIST']._serialized_end=277
  _globals['_ASSETTRAILREQUEST']._serialized_start=279
  _globals['_ASSETTRAILREQUEST']._serialized_end=316
  _globals['_ASSETTRAILRESPONSE']._serialized_start=318
  _globals['_ASSETTRAILRESPONSE']._serialized_end=405
  _globals['_GENERATEREPORTREQ']._serialized_start=407
  _globals['_GENERATEREPORTREQ']._serialized_end=444
  _globals['_TASKRESPONSE']._serialized_start=446
  _globals['_TASKRESPONSE']._serialized_end=510
  _globals['_TASKIDREQUEST']._serialized_start=512
  _globals['_TASKIDREQUEST']._serialized_end=544
  _globals['_TASKSTATUSRESPONSE']._serialized_start=546
  _globals['_TASKSTATUSRESPONSE']._serialized_end=633
  _globals['_FRAUDSCANREQUEST']._serialized_start=635
  _globals['_FRAUDSCANREQUEST']._serialized_end=653
  _globals['_AUDITSERVICE']._serialized_start=656
  _globals['_AUDITSERVICE']._serialized_end=1044
# @@protoc_insertion_point(module_scope)
