# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from core.grpc_generated import audit_pb2 as audit__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAuditLogs = channel.unary_unary(
                '/rwa.audit.AuditService/ListAuditLogs',
                request_serializer=audit__pb2.AuditListRequest.SerializeToString,
                response_deserializer=audit__pb2.AuditLogList.FromString,
                _registered_method=True)
        self.FetchAssetTrail = channel.unary_unary(
                '/rwa.audit.AuditService/FetchAssetTrail',
                request_serializer=audit__pb2.AssetTrailRequest.SerializeToString,
                response_deserializer=audit__pb2.AssetTrailResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/rwa.audit.AuditService/GenerateReport',
                request_serializer=audit__pb2.GenerateReportReq.SerializeToString,
                response_deserializer=audit__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetReportStatus = channel.unary_unary(
                '/rwa.audit.AuditService/GetReportStatus',
                request_serializer=audit__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=audit__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.TriggerFraudScan = channel.unary_unary(
                '/rwa.audit.AuditService/TriggerFraudScan',
                request_serializer=audit__pb2.FraudScanRequest.SerializeToString,
                response_deserializer=audit__pb2.TaskResponse.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListAuditLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAssetTrail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerFraudScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditLogs,
                    request_deserializer=audit__pb2.AuditListRequest.FromString,
                    response_serializer=audit__pb2.AuditLogList.SerializeToString,
            ),
            'FetchAssetTrail': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAssetTrail,
                    request_deserializer=audit__pb2.AssetTrailRequest.FromString,
                    response_serializer=audit__pb2.AssetTrailResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=audit__pb2.GenerateReportReq.FromString,
                    response_serializer=audit__pb2.TaskResponse.SerializeToString,
            ),
            'GetReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportStatus,
                    request_deserializer=audit__pb2.TaskIdRequest.FromString,
                    response_serializer=audit__pb2.TaskStatusResponse.SerializeToString,
            ),
            'TriggerFraudScan': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerFraudScan,
                    request_deserializer=audit__pb2.FraudScanRequest.FromString,
                    response_serializer=audit__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.audit.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.audit.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.audit.AuditService/ListAuditLogs',
            audit__pb2.AuditListRequest.SerializeToString,
            audit__pb2.AuditLogList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchAssetTrail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.audit.AuditService/FetchAssetTrail',
            audit__pb2.AssetTrailRequest.SerializeToString,
            audit__pb2.AssetTrailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.audit.AuditService/GenerateReport',
            audit__pb2.GenerateReportReq.SerializeToString,
            audit__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.audit.AuditService/GetReportStatus',
            audit__pb2.TaskIdRequest.SerializeToString,
            audit__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerFraudScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.audit.AuditService/TriggerFraudScan',
            audit__pb2.FraudScanRequest.SerializeToString,
            audit__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
