# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from core.grpc_generated import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """JWT passed in gRPC metadata: key "authorization", value "Bearer <token>"

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/rwa.auth.AuthService/Login',
                request_serializer=auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/rwa.auth.AuthService/Logout',
                request_serializer=auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/rwa.auth.AuthService/Refresh',
                request_serializer=auth__pb2.RefreshRequest.SerializeToString,
                response_deserializer=auth__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/rwa.auth.AuthService/GetMe',
                request_serializer=auth__pb2.GetMeRequest.SerializeToString,
                response_deserializer=auth__pb2.UserProfile.FromString,
                _registered_method=True)
        self.SetupMFA = channel.unary_unary(
                '/rwa.auth.AuthService/SetupMFA',
                request_serializer=auth__pb2.SetupMFARequest.SerializeToString,
                response_deserializer=auth__pb2.MFASetupResponse.FromString,
                _registered_method=True)
        self.EnableMFA = channel.unary_unary(
                '/rwa.auth.AuthService/EnableMFA',
                request_serializer=auth__pb2.MFAVerifyRequest.SerializeToString,
                response_deserializer=auth__pb2.MFAActionResponse.FromString,
                _registered_method=True)
        self.DisableMFA = channel.unary_unary(
                '/rwa.auth.AuthService/DisableMFA',
                request_serializer=auth__pb2.MFAVerifyRequest.SerializeToString,
                response_deserializer=auth__pb2.MFAActionResponse.FromString,
                _registered_method=True)
        self.ExportMyData = channel.unary_unary(
                '/rwa.auth.AuthService/ExportMyData',
                request_serializer=auth__pb2.ExportRequest.SerializeToString,
                response_deserializer=auth__pb2.UserDataExport.FromString,
                _registered_method=True)
        self.DeleteMyAccount = channel.unary_unary(
                '/rwa.auth.AuthService/DeleteMyAccount',
                request_serializer=auth__pb2.DeleteRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """JWT passed in gRPC metadata: key "authorization", value "Bearer <token>"

    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupMFA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableMFA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableMFA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportMyData(self, request, context):
        """GDPR Art. 15 — personal data export
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMyAccount(self, request, context):
        """GDPR Art. 17 — right to erasure (anonymises, does not hard-delete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__pb2.LoginRequest.FromString,
                    response_serializer=auth__pb2.TokenResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=auth__pb2.LogoutRequest.FromString,
                    response_serializer=auth__pb2.LogoutResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=auth__pb2.RefreshRequest.FromString,
                    response_serializer=auth__pb2.TokenResponse.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=auth__pb2.GetMeRequest.FromString,
                    response_serializer=auth__pb2.UserProfile.SerializeToString,
            ),
            'SetupMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupMFA,
                    request_deserializer=auth__pb2.SetupMFARequest.FromString,
                    response_serializer=auth__pb2.MFASetupResponse.SerializeToString,
            ),
            'EnableMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableMFA,
                    request_deserializer=auth__pb2.MFAVerifyRequest.FromString,
                    response_serializer=auth__pb2.MFAActionResponse.SerializeToString,
            ),
            'DisableMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableMFA,
                    request_deserializer=auth__pb2.MFAVerifyRequest.FromString,
                    response_serializer=auth__pb2.MFAActionResponse.SerializeToString,
            ),
            'ExportMyData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportMyData,
                    request_deserializer=auth__pb2.ExportRequest.FromString,
                    response_serializer=auth__pb2.UserDataExport.SerializeToString,
            ),
            'DeleteMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMyAccount,
                    request_deserializer=auth__pb2.DeleteRequest.FromString,
                    response_serializer=auth__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """JWT passed in gRPC metadata: key "authorization", value "Bearer <token>"

    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/Login',
            auth__pb2.LoginRequest.SerializeToString,
            auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/Logout',
            auth__pb2.LogoutRequest.SerializeToString,
            auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/Refresh',
            auth__pb2.RefreshRequest.SerializeToString,
            auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/GetMe',
            auth__pb2.GetMeRequest.SerializeToString,
            auth__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetupMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/SetupMFA',
            auth__pb2.SetupMFARequest.SerializeToString,
            auth__pb2.MFASetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/EnableMFA',
            auth__pb2.MFAVerifyRequest.SerializeToString,
            auth__pb2.MFAActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/DisableMFA',
            auth__pb2.MFAVerifyRequest.SerializeToString,
            auth__pb2.MFAActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportMyData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/ExportMyData',
            auth__pb2.ExportRequest.SerializeToString,
            auth__pb2.UserDataExport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.auth.AuthService/DeleteMyAccount',
            auth__pb2.DeleteRequest.SerializeToString,
            auth__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
