# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from core.grpc_generated import compliance_pb2 as compliance__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compliance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplianceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListComplianceRecords = channel.unary_unary(
                '/rwa.compliance.ComplianceService/ListComplianceRecords',
                request_serializer=compliance__pb2.PaginationRequest.SerializeToString,
                response_deserializer=compliance__pb2.ComplianceList.FromString,
                _registered_method=True)
        self.GetActiveAlerts = channel.unary_unary(
                '/rwa.compliance.ComplianceService/GetActiveAlerts',
                request_serializer=compliance__pb2.PaginationRequest.SerializeToString,
                response_deserializer=compliance__pb2.AlertList.FromString,
                _registered_method=True)
        self.GetComplianceStatus = channel.unary_unary(
                '/rwa.compliance.ComplianceService/GetComplianceStatus',
                request_serializer=compliance__pb2.UserIdRequest.SerializeToString,
                response_deserializer=compliance__pb2.ComplianceStatus.FromString,
                _registered_method=True)
        self.SubmitKYC = channel.unary_unary(
                '/rwa.compliance.ComplianceService/SubmitKYC',
                request_serializer=compliance__pb2.KYCSubmitRequest.SerializeToString,
                response_deserializer=compliance__pb2.KYCSubmitResponse.FromString,
                _registered_method=True)
        self.ApproveKYC = channel.unary_unary(
                '/rwa.compliance.ComplianceService/ApproveKYC',
                request_serializer=compliance__pb2.KYCApproveRequest.SerializeToString,
                response_deserializer=compliance__pb2.KYCApproveResponse.FromString,
                _registered_method=True)
        self.RunAMLScreening = channel.unary_unary(
                '/rwa.compliance.ComplianceService/RunAMLScreening',
                request_serializer=compliance__pb2.AMLScreeningRequest.SerializeToString,
                response_deserializer=compliance__pb2.AMLResult.FromString,
                _registered_method=True)


class ComplianceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListComplianceRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComplianceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitKYC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveKYC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunAMLScreening(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListComplianceRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComplianceRecords,
                    request_deserializer=compliance__pb2.PaginationRequest.FromString,
                    response_serializer=compliance__pb2.ComplianceList.SerializeToString,
            ),
            'GetActiveAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveAlerts,
                    request_deserializer=compliance__pb2.PaginationRequest.FromString,
                    response_serializer=compliance__pb2.AlertList.SerializeToString,
            ),
            'GetComplianceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComplianceStatus,
                    request_deserializer=compliance__pb2.UserIdRequest.FromString,
                    response_serializer=compliance__pb2.ComplianceStatus.SerializeToString,
            ),
            'SubmitKYC': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitKYC,
                    request_deserializer=compliance__pb2.KYCSubmitRequest.FromString,
                    response_serializer=compliance__pb2.KYCSubmitResponse.SerializeToString,
            ),
            'ApproveKYC': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveKYC,
                    request_deserializer=compliance__pb2.KYCApproveRequest.FromString,
                    response_serializer=compliance__pb2.KYCApproveResponse.SerializeToString,
            ),
            'RunAMLScreening': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAMLScreening,
                    request_deserializer=compliance__pb2.AMLScreeningRequest.FromString,
                    response_serializer=compliance__pb2.AMLResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.compliance.ComplianceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.compliance.ComplianceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplianceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListComplianceRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.compliance.ComplianceService/ListComplianceRecords',
            compliance__pb2.PaginationRequest.SerializeToString,
            compliance__pb2.ComplianceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.compliance.ComplianceService/GetActiveAlerts',
            compliance__pb2.PaginationRequest.SerializeToString,
            compliance__pb2.AlertList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComplianceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.compliance.ComplianceService/GetComplianceStatus',
            compliance__pb2.UserIdRequest.SerializeToString,
            compliance__pb2.ComplianceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitKYC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.compliance.ComplianceService/SubmitKYC',
            compliance__pb2.KYCSubmitRequest.SerializeToString,
            compliance__pb2.KYCSubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveKYC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.compliance.ComplianceService/ApproveKYC',
            compliance__pb2.KYCApproveRequest.SerializeToString,
            compliance__pb2.KYCApproveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunAMLScreening(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.compliance.ComplianceService/RunAMLScreening',
            compliance__pb2.AMLScreeningRequest.SerializeToString,
            compliance__pb2.AMLResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
