# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transactions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x12\x10rwa.transactions\"~\n\x0bListRequest\x12\x0f\n\x07tx_type\x18\x01 \x01(\t\x12\x0e\n\x06org_id\x18\x02 \x01(\t\x12\x17\n\x0fregulatory_flag\x18\x03 \x01(\x08\x12\x16\n\x0ehas_regulatory\x18\x04 \x01(\x08\x12\r\n\x05limit\x18\x05 \x01(\x05\x12\x0e\n\x06offset\x18\x06 \x01(\x05\"\x0e\n\x0cStatsRequest\"\x1e\n\x0cTxRefRequest\x12\x0e\n\x06tx_ref\x18\x01 \x01(\t\"\xed\x01\n\x13TransactionResponse\x12\x0e\n\x06tx_ref\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x61\x62ric_tx_id\x18\x02 \x01(\t\x12\x0f\n\x07tx_type\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x14\n\x0cinitiator_id\x18\x06 \x01(\t\x12\x15\n\rfrom_owner_id\x18\x07 \x01(\t\x12\x13\n\x0bto_owner_id\x18\x08 \x01(\t\x12\x17\n\x0fregulatory_flag\x18\t \x01(\x08\x12\x0e\n\x06status\x18\n \x01(\t\x12\x12\n\ncreated_at\x18\x0b \x01(\t\"N\n\x0fTransactionList\x12;\n\x0ctransactions\x18\x01 \x03(\x0b\x32%.rwa.transactions.TransactionResponse\"E\n\x10TransactionStats\x12\x1a\n\x12total_transactions\x18\x01 \x01(\x03\x12\x15\n\rvolume_frozen\x18\x02 \x01(\x01\x32\x9f\x02\n\x13TransactionsService\x12T\n\x10ListTransactions\x12\x1d.rwa.transactions.ListRequest\x1a!.rwa.transactions.TransactionList\x12Y\n\x13GetTransactionStats\x12\x1e.rwa.transactions.StatsRequest\x1a\".rwa.transactions.TransactionStats\x12W\n\x0eGetTransaction\x12\x1e.rwa.transactions.TxRefRequest\x1a%.rwa.transactions.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTREQUEST']._serialized_start=40
  _globals['_LISTREQUEST']._serialized_end=166
  _globals['_STATSREQUEST']._serialized_start=168
  _globals['_STATSREQUEST']._serialized_end=182
  _globals['_TXREFREQUEST']._serialized_start=184
  _globals['_TXREFREQUEST']._serialized_end=214
  _globals['_TRANSACTIONRESPONSE']._serialized_start=217
  _globals['_TRANSACTIONRESPONSE']._serialized_end=454
  _globals['_TRANSACTIONLIST']._serialized_start=456
  _globals['_TRANSACTIONLIST']._serialized_end=534
  _globals['_TRANSACTIONSTATS']._serialized_start=536
  _globals['_TRANSACTIONSTATS']._serialized_end=605
  _globals['_TRANSACTIONSSERVICE']._serialized_start=608
  _globals['_TRANSACTIONSSERVICE']._serialized_end=895
# @@protoc_insertion_point(module_scope)
