# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from core.grpc_generated import zkp_pb2 as zkp__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zkp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZKPServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetupKey = channel.unary_unary(
                '/rwa.zkp.ZKPService/SetupKey',
                request_serializer=zkp__pb2.SetupKeyRequest.SerializeToString,
                response_deserializer=zkp__pb2.SetupKeyResponse.FromString,
                _registered_method=True)
        self.VerifyProof = channel.unary_unary(
                '/rwa.zkp.ZKPService/VerifyProof',
                request_serializer=zkp__pb2.ProofRequest.SerializeToString,
                response_deserializer=zkp__pb2.ProofResponse.FromString,
                _registered_method=True)
        self.GetZKPStatus = channel.unary_unary(
                '/rwa.zkp.ZKPService/GetZKPStatus',
                request_serializer=zkp__pb2.StatusRequest.SerializeToString,
                response_deserializer=zkp__pb2.ZKPStatusResponse.FromString,
                _registered_method=True)
        self.RevokeCredential = channel.unary_unary(
                '/rwa.zkp.ZKPService/RevokeCredential',
                request_serializer=zkp__pb2.RevokeRequest.SerializeToString,
                response_deserializer=zkp__pb2.RevokeResponse.FromString,
                _registered_method=True)


class ZKPServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SetupKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetZKPStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetupKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupKey,
                    request_deserializer=zkp__pb2.SetupKeyRequest.FromString,
                    response_serializer=zkp__pb2.SetupKeyResponse.SerializeToString,
            ),
            'VerifyProof': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyProof,
                    request_deserializer=zkp__pb2.ProofRequest.FromString,
                    response_serializer=zkp__pb2.ProofResponse.SerializeToString,
            ),
            'GetZKPStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetZKPStatus,
                    request_deserializer=zkp__pb2.StatusRequest.FromString,
                    response_serializer=zkp__pb2.ZKPStatusResponse.SerializeToString,
            ),
            'RevokeCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCredential,
                    request_deserializer=zkp__pb2.RevokeRequest.FromString,
                    response_serializer=zkp__pb2.RevokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rwa.zkp.ZKPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rwa.zkp.ZKPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZKPService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetupKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.zkp.ZKPService/SetupKey',
            zkp__pb2.SetupKeyRequest.SerializeToString,
            zkp__pb2.SetupKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.zkp.ZKPService/VerifyProof',
            zkp__pb2.ProofRequest.SerializeToString,
            zkp__pb2.ProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetZKPStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.zkp.ZKPService/GetZKPStatus',
            zkp__pb2.StatusRequest.SerializeToString,
            zkp__pb2.ZKPStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rwa.zkp.ZKPService/RevokeCredential',
            zkp__pb2.RevokeRequest.SerializeToString,
            zkp__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
